kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        deployment: demo
    spec:
      containers:
        - name: demo
          image: docker.io/bitnami/apache
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
