apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
{{- with .Values.host }}
  host: {{ . }}
{{- end }}
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "generic-app.fullname" . }}

