apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <mirrors>
        <mirror>
          <id>maven.org</id>
          <name>Default mirror</name>
          <url>{{ .Values.build.mavenMirror | default "https://repo1.maven.org/maven2" }}</url>
          <mirrorOf>central</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
