apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: quarkus-getting-started
  name: admin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
  - kind: Group
    name: quarkus-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
