apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: operators-stable
placementBindingDefaults:
  name: operators-stable
policyDefaults:
  namespace: open-cluster-management-global-set
  placement:
    labelSelector:
      matchExpressions:
        - key: operator-lifecycle
          operator: In
          values:
            - stable
  policySets:
  - operators-stable
policies:
  - name: cert-manager
    disabled: false
    manifests:
      - path: cert-manager