apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-app
spec:
  project: default
  source:
    repoURL: http://gogs-gogs.apps.ocp-sno.lab.home/ken/gitops.git
    targetRevision: HEAD
    path: 4-cicd/generic-app
    helm:
      parameters:
      - name: image.name
        value: quarkus-getting-started
      - name: image.tag
        value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: devteam-dev
