apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: clusterconf
resources:
- ../../archetypes/sno
- ../../common/app-gitops
- ../../apps/demo
- ../../apps/quarkus-getting-started
patchesStrategicMerge:
- ingress-domain.yaml