apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: install-cert-manager-all-stable
spec:
  complianceType: musthave
  remediationAction: enforce
  severity: medium
  subscription:
    channel: stable-v1
    name: cert-manager-operator
    namespace: cert-manager-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    targetNamespaces:
      - cert-manager-operator
  upgradeApproval: Automatic
  versions: []