{{ with .Values.teamGitops -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.groupName }}
  namespace: {{ $.Values.gitopsNamespace }}
spec:
  source:
{{ . | toYaml | indent 4 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Values.gitopsNamespace }}
{{- end }}
