apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.gitopsNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.infraGitops }}
