{{ range .Values.namespaces -}} 
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.gitopsNamespace }}
{{- end }}
