{{ range $index, $namespace := .Values.namespaces -}}
{{ range $.Values.groups -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ $namespace.name }}
  name: {{ .role | default "edit" }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
  - kind: Group
    name: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .role | default "edit" }}
{{ end }}
{{ end }}
