apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: openshift-gitops
spec:
  project: demo
  source:
    repoURL: http://gogs-gogs.apps.ocp-sno.lab.home/ken/gitops.git
    targetRevision: HEAD
    path: 3-apps/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
