apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cert-manager/

patches:
  - target:
      kind: OperatorPolicy
      name: install-cert-manager
    patch: |
      - op: replace
        path: /spec/subscription/channel
        value: stable-v1
      # Repeat block for each added version
      - op: add
        path: /spec/versions/
        value: "cert-manager-operator.v1.18.0"