apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator

policyDefaults:
  placement:
    labelSelector:
      matchExpressions:
        - key: operator-lifecycle
          operator: In
          values:
            - next
  policySets:
  - operators-next
policies:
  - name: cert-manager-next
    disabled: false
    manifests:
      - path: cert-manager