# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

groupName: devteam

infraGitops: openshift-gitops
gitopsNamespace: devteam-gitops

teamGitops:
  repoURL: https://github.com/devteam/gitops.git
  targetRevision: HEAD
#  path: gitops/

namespaces:
  - name: devteam-dev
    quota: medium
  - name: devteam-test
    quota: medium
